// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: get_dish.proto

package get_dish_serv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishRequest) Reset() {
	*x = DishRequest{}
	mi := &file_get_dish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishRequest) ProtoMessage() {}

func (x *DishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishRequest.ProtoReflect.Descriptor instead.
func (*DishRequest) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{0}
}

func (x *DishRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DishesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishesResponse) Reset() {
	*x = DishesResponse{}
	mi := &file_get_dish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishesResponse) ProtoMessage() {}

func (x *DishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishesResponse.ProtoReflect.Descriptor instead.
func (*DishesResponse) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{1}
}

func (x *DishesResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type Dish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category      *Category              `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	NutFact       *NutritionFact         `protobuf:"bytes,5,opt,name=nut_fact,json=nutFact,proto3" json:"nut_fact,omitempty"`
	Tag           *Tag                   `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	Recipe        string                 `protobuf:"bytes,7,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_get_dish_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{2}
}

func (x *Dish) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Dish) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Dish) GetNutFact() *NutritionFact {
	if x != nil {
		return x.NutFact
	}
	return nil
}

func (x *Dish) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Dish) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeDish      string                 `protobuf:"bytes,2,opt,name=type_dish,json=typeDish,proto3" json:"type_dish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_get_dish_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{3}
}

func (x *Type) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Type) GetTypeDish() string {
	if x != nil {
		return x.TypeDish
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryDish  string                 `protobuf:"bytes,2,opt,name=category_dish,json=categoryDish,proto3" json:"category_dish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_get_dish_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetCategoryDish() string {
	if x != nil {
		return x.CategoryDish
	}
	return ""
}

type NutritionFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Calories      float32                `protobuf:"fixed32,2,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins      float32                `protobuf:"fixed32,3,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats          float32                `protobuf:"fixed32,4,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbohydrates float32                `protobuf:"fixed32,5,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutritionFact) Reset() {
	*x = NutritionFact{}
	mi := &file_get_dish_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionFact) ProtoMessage() {}

func (x *NutritionFact) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionFact.ProtoReflect.Descriptor instead.
func (*NutritionFact) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{5}
}

func (x *NutritionFact) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NutritionFact) GetCalories() float32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *NutritionFact) GetProteins() float32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *NutritionFact) GetFats() float32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *NutritionFact) GetCarbohydrates() float32 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagDish       string                 `protobuf:"bytes,2,opt,name=tag_dish,json=tagDish,proto3" json:"tag_dish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_get_dish_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_get_dish_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_get_dish_proto_rawDescGZIP(), []int{6}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetTagDish() string {
	if x != nil {
		return x.TagDish
	}
	return ""
}

var File_get_dish_proto protoreflect.FileDescriptor

const file_get_dish_proto_rawDesc = "" +
	"\n" +
	"\x0eget_dish.proto\x12\x06dishes\"\x1d\n" +
	"\vDishRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"6\n" +
	"\x0eDishesResponse\x12$\n" +
	"\x06dishes\x18\x01 \x03(\v2\f.dishes.DishR\x06dishes\"\xe3\x01\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\x04type\x18\x03 \x01(\v2\f.dishes.TypeR\x04type\x12,\n" +
	"\bcategory\x18\x04 \x01(\v2\x10.dishes.CategoryR\bcategory\x120\n" +
	"\bnut_fact\x18\x05 \x01(\v2\x15.dishes.NutritionFactR\anutFact\x12\x1d\n" +
	"\x03tag\x18\x06 \x01(\v2\v.dishes.TagR\x03tag\x12\x16\n" +
	"\x06recipe\x18\a \x01(\tR\x06recipe\"3\n" +
	"\x04Type\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\ttype_dish\x18\x02 \x01(\tR\btypeDish\"?\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rcategory_dish\x18\x02 \x01(\tR\fcategoryDish\"\x91\x01\n" +
	"\rNutritionFact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bcalories\x18\x02 \x01(\x02R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x03 \x01(\x02R\bproteins\x12\x12\n" +
	"\x04fats\x18\x04 \x01(\x02R\x04fats\x12$\n" +
	"\rcarbohydrates\x18\x05 \x01(\x02R\rcarbohydrates\"0\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\btag_dish\x18\x02 \x01(\tR\atagDish2G\n" +
	"\vDishService\x128\n" +
	"\tGetDishes\x12\x13.dishes.DishRequest\x1a\x16.dishes.DishesResponseB\x10Z\x0e/get_dish_servb\x06proto3"

var (
	file_get_dish_proto_rawDescOnce sync.Once
	file_get_dish_proto_rawDescData []byte
)

func file_get_dish_proto_rawDescGZIP() []byte {
	file_get_dish_proto_rawDescOnce.Do(func() {
		file_get_dish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_dish_proto_rawDesc), len(file_get_dish_proto_rawDesc)))
	})
	return file_get_dish_proto_rawDescData
}

var file_get_dish_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_get_dish_proto_goTypes = []any{
	(*DishRequest)(nil),    // 0: dishes.DishRequest
	(*DishesResponse)(nil), // 1: dishes.DishesResponse
	(*Dish)(nil),           // 2: dishes.Dish
	(*Type)(nil),           // 3: dishes.Type
	(*Category)(nil),       // 4: dishes.Category
	(*NutritionFact)(nil),  // 5: dishes.NutritionFact
	(*Tag)(nil),            // 6: dishes.Tag
}
var file_get_dish_proto_depIdxs = []int32{
	2, // 0: dishes.DishesResponse.dishes:type_name -> dishes.Dish
	3, // 1: dishes.Dish.type:type_name -> dishes.Type
	4, // 2: dishes.Dish.category:type_name -> dishes.Category
	5, // 3: dishes.Dish.nut_fact:type_name -> dishes.NutritionFact
	6, // 4: dishes.Dish.tag:type_name -> dishes.Tag
	0, // 5: dishes.DishService.GetDishes:input_type -> dishes.DishRequest
	1, // 6: dishes.DishService.GetDishes:output_type -> dishes.DishesResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_get_dish_proto_init() }
func file_get_dish_proto_init() {
	if File_get_dish_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_dish_proto_rawDesc), len(file_get_dish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_dish_proto_goTypes,
		DependencyIndexes: file_get_dish_proto_depIdxs,
		MessageInfos:      file_get_dish_proto_msgTypes,
	}.Build()
	File_get_dish_proto = out.File
	file_get_dish_proto_goTypes = nil
	file_get_dish_proto_depIdxs = nil
}
