/*
 * Catering service
 *
 * Menu service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	createdish "github.com/KusakinDev/Catering-Menu-Service/internal/handlers/create_dish"
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /CreateDish
// Create new position in menu
func (api *DefaultAPI) CreateDishPost(c *gin.Context) {

	code, message := createdish.CreateDish(c)

	c.JSON(code, gin.H{"message": message})
}
