/*
 * Catering service
 *
 * Menu service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /CreateDish
// Create new position in menu
func (api *DefaultAPI) CreateDishPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
