FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main ./migrate/source/migrate_all_models/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache bash

COPY --from=builder /app/main .

COPY scripts/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["/wait-for-it.sh", "db:5432", "--", "./main"]