/*
 * Catering service
 *
 * Menu service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateDishPostRequest struct {

	Name string `json:"name,omitempty"`

	Recipe string `json:"recipe,omitempty"`
}
