/*
 * Catering service
 *
 * Menu service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateDishPost200Response struct {

	Message string `json:"message,omitempty"`
}
